name: Terraform Plan on PR

on:
  pull_request:
    branches:
      - main # Or your default branch

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write # Required to post plan as a comment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ap-south-1
      - name: test
        run: aws sts get-caller-identity
     
